# Generated by Django 5.0.7 on 2024-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
        ),
    ]
