# Generated by Django 5.0.7 on 2024-09-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=127)),
                ('eircode', models.CharField(blank=True, choices=[('DO2 PN40', 'DO2 PN40'), ('H91 E2R8', 'H91 E2R8'), ('T23 E6TD', 'T23 E6TD'), ('C15 H04P', 'C15 H04P')], default='DO2 PN40', max_length=200, null=True)),
                ('city', models.CharField(default='Dublin', max_length=127)),
                ('country', models.CharField(blank=True, default='Ireland', max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('tech', models.CharField(blank=True, max_length=127, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('text_used', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('cislack', 'CISLACK'), ('dm', 'DM'), ('indeed', 'INDEED'), ('lkeasy', 'LKEASY'), ('lkpsearch', 'LKPSearch'), ('jobs.ie', 'JOBS.IE'), ('lkjobsug', 'LKJOBSUG'), ('inform', 'INFORM'), ('irishjobs.ie', 'IRISHJOBS.IE'), ('seekrefr', 'SEEKREFR')], default='dm', max_length=127, null=True)),
                ('status', models.CharField(choices=[('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG'), ('pending<wk', 'PENDING<WK'), ('pending<2wk', 'PENDING<2WK'), ('pend<MONTH', 'PEND<MONTH'), ('pend+month', 'PEND+MONTH')], default='pending<wk', max_length=127, null=True)),
                ('search_imgs', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d')),
                ('docfile', models.FileField(blank=True, upload_to='static/documents/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lng', models.CharField(blank=True, max_length=200, null=True)),
                ('place_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lkdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('srch_appears', models.IntegerField(blank=True, null=True)),
                ('uni_views', models.IntegerField(blank=True, null=True)),
                ('engagements', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
