# Generated by Django 5.0.7 on 2024-07-17 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='email',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='jobsearch',
            old_name='phone',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='jobsearch',
            old_name='first_name',
            new_name='organistion',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='last_name',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='response',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='search_imgs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='text_used',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
