# Generated by Django 5.0.7 on 2024-07-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_email_jobsearch_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='organistion',
            new_name='organisation',
        ),
    ]
