# Generated by Django 5.0.7 on 2024-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_organistion_jobsearch_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='search_imgs',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
