# Generated by Django 5.0.7 on 2024-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobsearch_search_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
