# Generated by Django 5.0.7 on 2024-07-18 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobsearch_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
