# Generated by Django 5.0.7 on 2024-07-21 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobsearch_method_alter_jobsearch_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=127),
            preserve_default=False,
        ),
    ]
