# Generated by Django 5.0.7 on 2024-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsearch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='type',
            field=models.CharField(blank=True, choices=[('private', 'PRIVATE'), ('public', 'PUBLIC'), ('local', 'LOCAL')], default='private', max_length=127, null=True),
        ),
    ]
