# Generated by Django 5.0.7 on 2024-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobsearch_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='docfile',
            field=models.FileField(blank=True, upload_to='static/documents/%Y/%m/%d'),
        ),
    ]
