# Generated by Django 5.0.7 on 2024-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobsearch_search_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='search_imgs',
            field=models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d'),
        ),
    ]
