# Generated by Django 5.0.7 on 2024-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobsearch_search_imgs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='method',
            field=models.CharField(blank=True, choices=[('lkeasy', 'LKEASY'), ('lkpsearch', 'LKPSearch'), ('cislack', 'CISLACK'), ('lkjobsug', 'LKJOBSUG'), ('inform', 'INFORM'), ('irishjobs.ie', 'IRISHJOBS.IE')], default='lkeasy', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='text_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
