# Generated by Django 5.0.7 on 2024-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobsearch_options_alter_jobsearch_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='type',
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='response',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('interview', 'INTERVIEW')], default='pending', max_length=127, null=True),
        ),
    ]
