# Generated by Django 5.0.7 on 2024-07-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_jobsearch_contact_remove_jobsearch_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsearch',
            options={'ordering': ['-created_at', 'response']},
        ),
    ]
