# Generated by Django 5.0.7 on 2024-08-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobsearch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='response',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER')], default='pending', max_length=127, null=True),
        ),
    ]
