# Generated by Django 5.0.7 on 2024-08-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_co2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CO2',
            new_name='Lkdata',
        ),
    ]
