# Generated by Django 5.0.7 on 2024-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_rename_co2_lkdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkdata',
            name='average',
        ),
        migrations.AddField(
            model_name='lkdata',
            name='engagements',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lkdata',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lkdata',
            name='impressions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lkdata',
            name='unique_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
