# Generated by Django 5.0.7 on 2024-08-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_remove_lkdata_average_lkdata_engagements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkdata',
            old_name='unique_views',
            new_name='srch_appears',
        ),
        migrations.AddField(
            model_name='lkdata',
            name='uni_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
