# Generated by Django 5.0.7 on 2024-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_rename_unique_views_lkdata_srch_appears_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='jobsearch',
            old_name='organisation',
            new_name='name',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
