# Generated by Django 5.0.7 on 2024-08-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_rename_location_jobsearch_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='response',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='url',
        ),
    ]
