# Generated by Django 5.0.7 on 2024-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_rename_response_jobsearch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='method',
            field=models.CharField(blank=True, choices=[('indeed', 'INDEED'), ('lkeasy', 'LKEASY'), ('lkpsearch', 'LKPSearch'), ('cislack', 'CISLACK'), ('lkjobsug', 'LKJOBSUG'), ('inform', 'INFORM'), ('irishjobs.ie', 'IRISHJOBS.IE')], default='lkeasy', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG')], default='pending', max_length=127, null=True),
        ),
    ]
