# Generated by Django 5.0.7 on 2024-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_alter_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG'), ('pending<wk', 'PENDING<WK'), ('1week', '1WEEK'), ('2week', '2WEEK'), ('1month', '1MONTH')], default='pending', max_length=127, null=True),
        ),
    ]
