# Generated by Django 5.0.7 on 2024-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_alter_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
