# Generated by Django 5.0.7 on 2024-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_jobsearch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG')], default='pending', max_length=127, null=True),
        ),
    ]
