# Generated by Django 5.0.7 on 2024-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_alter_jobsearch_created_at_alter_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='method',
            field=models.CharField(blank=True, choices=[('cislack', 'CISLACK'), ('dm', 'DM'), ('indeed', 'INDEED'), ('lkeasy', 'LKEASY'), ('lkpsearch', 'LKPSearch'), ('jobs.ie', 'JOBS.IE'), ('lkjobsug', 'LKJOBSUG'), ('inform', 'INFORM'), ('irishjobs.ie', 'IRISHJOBS.IE')], default='dm', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('pending1mnt', 'PENDING1MNT'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG'), ('pending<wk', 'PENDING<WK'), ('1week', '1WEEK'), ('2week', '2WEEK'), ('1month', '1MONTH')], default='pending', max_length=127, null=True),
        ),
    ]
