# Generated by Django 5.0.7 on 2024-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_alter_jobsearch_created_at_alter_jobsearch_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG'), ('pending<wk', 'PENDING<WK'), ('pending<2wk', 'PENDING<2WK'), ('pend<MONTH', 'PEND<MONTH'), ('pend+month', 'PEND+MONTH')], default='pending', max_length=127, null=True),
        ),
    ]
