# Generated by Django 5.0.7 on 2024-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_alter_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='city',
            field=models.CharField(default='Dublin', max_length=127),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='country',
            field=models.CharField(blank=True, default='Ireland', max_length=200, null=True),
        ),
    ]
