# Generated by Django 5.0.7 on 2024-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_jobsearch_city_alter_jobsearch_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='zipcode',
            new_name='eircode',
        ),
    ]
