# Generated by Django 5.0.7 on 2024-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_rename_zipcode_jobsearch_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='eircode',
            field=models.CharField(blank=True, default='DO2 PN40', max_length=200, null=True),
        ),
    ]
