# Generated by Django 5.0.7 on 2024-08-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_jobsearch_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='eircode',
            field=models.CharField(blank=True, choices=[('DO2 PN40', 'DO2 PN40'), ('H91 E2R8', 'H91 E2R8'), ('T23 E6TD', 'T23 E6TD'), ('C15 H04P', 'C15 H04P')], default='DO2 PN40', max_length=200, null=True),
        ),
    ]
