# Generated by Django 5.0.7 on 2024-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_alter_jobsearch_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(blank=True, choices=[('not_proceeding', 'NOT_PROCEEDING'), ('pre_int_screen', 'PRE_INT_SCREEN'), ('interview', 'INTERVIEW'), ('offer', 'OFFER'), ('appinprog', 'APPINPROG'), ('pending<wk', 'PENDING<WK'), ('pending<2wk', 'PENDING<2WK'), ('pend<MONTH', 'PEND<MONTH'), ('pend+month', 'PEND+MONTH')], default='pending<wk', max_length=127, null=True),
        ),
    ]
