# Generated by Django 5.0.7 on 2024-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_alter_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='method',
            field=models.CharField(blank=True, choices=[('cislack', 'CISLACK'), ('dm', 'DM'), ('indeed', 'INDEED'), ('lkeasy', 'LKEASY'), ('lkpsearch', 'LKPSearch'), ('jobs.ie', 'JOBS.IE'), ('lkjobsug', 'LKJOBSUG'), ('inform', 'INFORM'), ('irishjobs.ie', 'IRISHJOBS.IE'), ('seekrefr', 'SEEKREFR')], default='dm', max_length=127, null=True),
        ),
    ]
