# Generated by Django 5.0.7 on 2024-08-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='adress',
            new_name='address',
        ),
    ]
