# Generated by Django 5.0.7 on 2024-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_adress_locations_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='zipcode',
            new_name='eircode',
        ),
    ]
