# Generated by Django 5.0.7 on 2024-09-24 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 24, 9, 53, 40, 275962, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
