# Generated by Django 5.0.7 on 2024-09-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthtoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='created_at',
        ),
    ]
